feat(EU): Support setting the charging current
Hyundai-Kia-Connect/kia_uvo pull request #896
Opened 2024-06-24 19:43 UTC by jrnk

Following up with this to support https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/632951ff7a970541dec7bcde0960c47bcbaa71a2 

Should solve https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/864

Note: I've translated all but the Chinese (that was missing more translation keys), but the indentation seems to be different for every localization which was a bit cumbersome, but I didn't want to clutter this commit with formatting.

2024-06-24 20:21 UTC, cdnninja commented
Looks good.  Would it be worth adding a sensor to display it? Either a number slider so you can edit or just a sensor to display.  

Number with edit may be hard since only a few values work, I guess drop down menu could be an option too.

2024-06-24 20:23 UTC, jrnk commented
Yes, good idea, will add it!

2024-06-24 20:26 UTC, cdnninja commented
Same pr or different?

2024-06-24 20:26 UTC, cdnninja commented
Also the manifest file needs to be updated to the new api version.

2024-06-24 20:28 UTC, jrnk commented
> Also the manifest file needs to be updated to the new api version.

All will be in this PR, already bumped the version in the manifest

2024-06-24 20:40 UTC, jrnk commented
@cdnninja added the sensor, also needed to add a mapping function for it, if you have another suggestion to do this: please shoot, this is new for me ;)

2024-06-24 20:42 UTC, jrnk commented
> Number with edit may be hard since only a few values work, I guess drop down menu could be an option too.

The selector was already added in `services.yml`, does it need more for it to work?

2024-06-24 22:16 UTC, cdnninja commented
> > Number with edit may be hard since only a few values work, I guess drop down menu could be an option too.
> 
> 
> 
> The selector was already added in `services.yaml`, does it need more for it to work?
> 
> 
> 
> 


Services work but people often want it on the dashboard.  We can do without though, you have done the heavy lift.

2024-06-24 22:17 UTC, cdnninja commented
> > Number with edit may be hard since only a few values work, I guess drop down menu could be an option too.
> 
> 
> 
> The selector was already added in `services.yaml`, does it need more for it to work?
> 
> 
> 
> 

Mapping is often done as enum in the constants file in both the api and home assistant files.

2024-06-24 23:41 UTC, cdnninja requested changes
Here is a bit of feedback. It is very close! You have learned quick.   Help on this integration is appreciated this I no longer have one of these cars.

2024-06-24 23:41 UTC, cdnninja commented on custom_components/kia_uvo/sensor.py
> +        name="Charging current limit",
We use capitals for each letter for exposed names.

2024-06-24 23:41 UTC, cdnninja commented on custom_components/kia_uvo/sensor.py
> +    mapping = {1: 100, 2: 90, 3: 60}
This should move to constants.

2024-06-24 23:41 UTC, cdnninja commented on custom_components/kia_uvo/services.yaml
> +              value: 1
Not sure why but the CI isn't happy with this: https://github.com/Hyundai-Kia-Connect/kia_uvo/actions/runs/9652140110/job/26621566236

2024-06-25 23:20 UTC, merged

2024-06-27 19:52 UTC, jrnk commented
@tobixx yes saw that! Fixed in https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/581

2024-06-28 06:54 UTC, jrnk commented
@tobixx ah I missed you could not set it in the app, then it's not available for the EV6 I guess. For an EV9 you can control this current in the app on the "EV service" page. 

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5436814/a08006ec-14b0-467a-be29-6ecb8e5c8158)